### recuperer todos los clientes
GET http://localhost:3001/clients/

### agregar cliente
POST http://localhost:3001/clients/add
content-type: application/json

{
    "id": "1129574805",
    "nombre": "Jorge Luchetta",
    "telefono": "3012723018",
    "email": "jluchett@gmail.com"
}

### recuperar todos los usuarios
GET http://localhost:3001/users/

### recuperar vehiculos
GET http://localhost:3001/vehicles/

### registrar vehculo
POST   http://localhost:3001/vehicles/add
content-type: application/json

{
    "placa": "GNV321",
    "marca": "Chevrolet",
    "modelo": "corsa",
    "anio": 2004,
    "kilometraje": 80000,
    "motor": 2000,
    "transmision": "Manual",
    "cliente_id": "1129574805"
}

### Actualizar vehiculo 
PUT  http://localhost:3001/vehicles/update/GNV321
content-type: application/json

{
    "placa": "GNV321",
    "marca": "Chevrolet",
    "modelo": "corsa",
    "anio": 2004,
    "kilometraje": 80000,
    "motor": 2000,
    "transmision": "Manual",
    "cliente_id": "1129574805"
}

### eliminar vehiculo
DELETE   http://localhost:3001/vehicles/delete/ZAB40E

### obtener productos
GET http://localhost:3001/products/

### Agregar producto a la base de  datos
POST http://localhost:3001/products/add
content-type: application/json

{
    "nombre": "Cambio de aceite",
    "precio": 100000
}
