### recuperer todos los clientes
GET http://localhost:3001/clients/

### agregar cliente
POST http://localhost:3001/clients/add
content-type: application/json

{
    "id": "84025820",
    "nombre": "ARIEL DE LUQUE RODRIGUEZ",
    "telefono": "3174360315",
    "email": ""
}

### actualizar cliente
PUT  http://localhost:3001/clients/update/84025820
content-type: application/json

{
    "nombre": "ARIEL DE LUQUE RODRIGUEZ",
    "telefono": "3174360315",
    "email": "No registra"
}

### recuperar todos los usuarios
GET http://localhost:3001/users/

### recuperar un usuario especifico por id
GET http://localhost:3001/users/1129574805


### Crear usuario
POST  http://localhost:3001/users/create
content-type: application/json

{
    "id": "39089832",
    "name": "Libia Annichiarico",
    "password": "Ciao1234"
}

### Bloquear usuario por su id
PUT   http://localhost:3001/users/locked/39089832
content-type: application/json

{
    "locked": true
}

### actualizar usuario por su id
POST  http://localhost:3001/users/update/39089832
content-type: application/json

{
    "name": "Libia Maria Annichiarico",
    "role": "vendedor"
}

### recuperar vehiculos
GET   http://localhost:3001/vehicles/

### registrar vehculo
POST  http://localhost:3001/vehicles/add
content-type: application/json

{
    "placa": "CRL690",
    "marca": "FORD",
    "modelo": "SPORTAGE",
    "anio": 2010,
    "kilometraje": 177252,
    "motor": 2400,
    "transmision": "Manual",
    "cliente_id": "84025820"
}

### Actualizar vehiculo 
PUT  http://localhost:3001/vehicles/update/GNV321
content-type: application/json

{
    "placa": "GNV321",
    "marca": "Chevrolet",
    "modelo": "corsa",
    "anio": 2004,
    "kilometraje": 80000,
    "motor": 2000,
    "transmision": "Manual",
    "cliente_id": "1129574805"
}

### eliminar vehiculo
DELETE   http://localhost:3001/vehicles/delete/ZAB40E

### obtener productos
GET http://localhost:3001/products/

### Agregar producto a la base de  datos
POST http://localhost:3001/products/add
content-type: application/json

{
    "nombre": "Motor Elf 5W20 1/4",
    "precio": 64000
}

### actualizar producto
PUT  http://localhost:3001/products/update/1
content-type: application/json

{
    "nombre": "Sin",
    "precio": 98000
}

### eliminar producto
DELETE   http://localhost:3001/products/delete/3


### recuperer todas las ordenes
GET http://localhost:3001/orders

### Agregar Orden a la base de  datos
POST http://localhost:3001/orders/add
content-type: application/json

{
  "fecha_orden": "now",
  "id_cliente": "84025820",
  "placa_vehic": "CRL690",
  "total_orden": 139000,
  "detalle": [
    {
      "producto_id": 2,
      "cantidad": 1,
      "precio_unitario": 55000
    },
    {
      "producto_id": 15,
      "cantidad": 1,
      "precio_unitario": 20000
    },
    {
      "producto_id": 23,
      "cantidad": 1,
      "precio_unitario": 64000
    }
  ]
}

### eliminar prodOrdenucto
DELETE   http://localhost:3001/orders/delete/3

### Obtener detalle ordenes
GET    http://localhost:3001/orders/detail/2